### ISSUE TITLE
Does game Pendulum really need take up to 1 hour to converge?

### ISSUE THREAD

**Issue by dbsxdbsx** [timoklein/alphazero-gym#6]
I notice the statement in README: " If your laptop is decent it shouldn't take more than an hour.", here I have no idea how long pendulum would take to converge in common.   (Since from papers I read, rare of them plot a chart of pendulum, so I have no idea.)
And even more,  what does "convergence" mean in the context of pendulum?   
Do you mean that with your algorithm, the pendulum would converge to near 0 (the best score) with 1-hour of training?

Personally, with raw SAC,  I could make pendulum converge to a range around [-500,-200)  within 1 minute on laptop of a Geforce 940M GPU. And it is hard to make the score better, even with more training time.

**Comment by timoklein** [comment]
> Personally, with raw SAC, I could make pendulum converge to a range around [-500,-200)

It's the same for this repo. With a bit of hyperparameter tuning you can get to around -200 repeatedly.

> 1 minute on laptop of a Geforce 940M GPU

If your laptop has a GPU, I'd say it's well above average :) The one hour refers to e.g. your standard Intel built-in graphics. AlphaZero will still be a lot slower than SAC though due to the planning required at every time step. MCTS rollouts in Python are just very slow...
You can try to adapt the `n_rollouts` parameter in the MCTS config and see if you can lower it without affecting performance. That's the parameter affecting training throughput the most.

**Comment by dbsxdbsx** [comment]
I see, thanks for your answer.
